### ISSUE TITLE
Migrate issues from BitBucket

### ISSUE THREAD

**Issue by oznogon** [devdogio/Inventory-Pro#1]
There are several issues in the [BitBucket repo linked to in the documentation](https://bitbucket.org/jjahuijbregts/inventorypro/issues?status=new&status=open&sort=-created_on) that the community could start addressing.

https://github.com/jeffwidman/bitbucket-issue-migration can help facilitate moving issues over.

**Comment by bsimser** [comment]
I've done this in my own fork [here](https://github.com/bsimser/Inventory-Pro) I feel the devdog guys have basically abandoned this repo so I'm planning going forward with fixes for my own use and will keep my repo up to date (and go through the issues fixing what I can when I have time). I've also done this for Quest System Pro, general, Rucksack, and created a general2 repo (which is required for Rucksack) that devdog still hasn't brought over to github.
